//#pragma config(Motor,  motorB,          MotorB,        tmotorEV3_Medium, PIDControl, driveRight, encoder)
//#pragma config(Motor,  motorC,          MotorC,        tmotorEV3_Medium, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{int grey1=45, grey2=45;
	int G=25, B=25;
	string Le, Pr;
	Le = SensorValue[S2];
	Pr = SensorValue[S3];
while(true){
	if(SensorValue[S2]>grey1) //2L 3R
{if(SensorValue[S3]>grey2)
{motor[motorB]=G; motor[motorC]=-G;
																// setMotorSyncEncoder(motorB, motorC, 0, 50, 25);
						displayString(0, "Go go! %d", Le);
						displayString(1, "Go go! %d", Pr);
}
else{motor[motorB]=-G; motor[motorC]=-B;
																//setMotorSyncEncoder(motorB, motorC, 25, 50, 25);
						displayString(0, "Right! %d", Le);
						displayString(1, "Right! %d", Pr);
}}
else{if(SensorValue[S3]>grey2)
	{motor[motorB]=B; motor[motorC]=G;
																//setMotorSyncEncoder(motorB, motorC, -25, 50, 25);
						displayString(0, "Left! %d", Le);
						displayString(1, "Left! %d", Pr);
	}else
	{motor[motorB]=G; motor[motorC]=-G;
																//setMotorSyncEncoder(motorB, motorC, 0, 0, 0);
displayString(0, "Blind! %d", Le);
displayString(1, "Blind! %d", Pr);
}}
//wait1Msec(1);

}}
