#pragma config(Sensor, S1,     ,               sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     ,               sensorEV3_Color)
#pragma config(Sensor, S3,     ,               sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Motor,  motorB,          MotorB,        tmotorEV3_Medium, PIDControl, driveRight, encoder)
//#pragma config(Motor,  motorC,          MotorC,        tmotorEV3_Medium, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{int grey1=45, grey2=45;
	int G=25, B=25, S=25;
	string Le, Pr;
	Le = SensorValue[S2];
	Pr = SensorValue[S3];
while(true){
	if(SensorValue[S1]<S){
		motor[motorB]=0;
		motor[motorC]=0;}
		else{
	if(SensorValue[S2]>grey1) //2L 3R BR CL
{if(SensorValue[S3]>grey2)
{motor[motorB]=G; motor[motorC]=G;

}
else{motor[motorB]=-G; motor[motorC]=B;
																//setMotorSyncEncoder(motorB, motorC, 25, 50, 25);
						displayString(0, "Right! %d", Le);
						displayString(1, "Right! %d", Pr);
}}
else{if(SensorValue[S3]>grey2)
	{motor[motorB]=B; motor[motorC]=-G;
																//setMotorSyncEncoder(motorB, motorC, -25, 50, 25);
						displayString(0, "Left! %d", Le);
						displayString(1, "Left! %d", Pr);
	}else
	{motor[motorB]=G; motor[motorC]=G;
																//setMotorSyncEncoder(motorB, motorC, 0, 0, 0);
displayString(0, "Blind! %d", Le);
displayString(1, "Blind! %d", Pr);
}}}
//wait1Msec(1);

}}
